#pragma once

// From glfw3.h
#define ALPHA_MOUSE_BUTTON_1         0
#define ALPHA_MOUSE_BUTTON_2         1
#define ALPHA_MOUSE_BUTTON_3         2
#define ALPHA_MOUSE_BUTTON_4         3
#define ALPHA_MOUSE_BUTTON_5         4
#define ALPHA_MOUSE_BUTTON_6         5
#define ALPHA_MOUSE_BUTTON_7         6
#define ALPHA_MOUSE_BUTTON_8         7
#define ALPHA_MOUSE_BUTTON_LAST      ALPHA_MOUSE_BUTTON_8
#define ALPHA_MOUSE_BUTTON_LEFT      ALPHA_MOUSE_BUTTON_1
#define ALPHA_MOUSE_BUTTON_RIGHT     ALPHA_MOUSE_BUTTON_2
#define ALPHA_MOUSE_BUTTON_MIDDLE    ALPHA_MOUSE_BUTTON_3